# Site settings
title: Android Testing Support Library
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official page for the Android Testing Support Library, a library provided by Google for testing Android apps.
baseurl: "/android-testing-support-library" # the subpath of your site, e.g. /blog/
url: "https://google.github.io" # the base hostname & protocol for your site
sourceUrl: "https://android.googlesource.com/platform/frameworks/testing/+/android-support-test/"

# Build settings
markdown: kramdown

# Define version numbers for library artifacts
atslVersion: 0.5
espressoVersion: 2.2.2
uiautomatorVersion: 2.1.2

gems:
  - octopress-autoprefixer
  - jekyll-redirect-from
